repos:
-   repo: https://github.com/python/black
    rev: 23.10.1
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
    -   id: ruff
