name: Development Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  lint_and_test:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11" ]
        mpi: [ 'mpich' ]
    name: lint with python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup MPI # https://github.com/mpi4py/setup-mpi
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]
      - name: Lint check with ruff
        run: |
          ruff --target-version=py311 --line-length 79 ./
      - name: Style check with black
        run: |
          black ./ --check --line-length 79
      - name: Run tests with pytest (serial)
        run: |
          pytest -s tests/units
      - name: Run tests with pytest (parallel)
        run: |
          mpirun -n 2 --use-hwthread-cpus pytest -s tests/units --with-mpi
