name: Development Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    name: lint with python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]
      - name: Lint check with ruff
        run: |
          ruff --target-version=py311 --line-length 90 ./
      - name: Style check with black
        run: |
          black ./ --check --line-length 79
      - name: Run unit tests with pytest
        run: |
          pytest -s tests/units
