name: Development tests

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  lint_and_test:
    strategy:
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.11" ]
        mpi: [ 'mpich' ]
    name: Test with Python ${{ matrix.python-version }} on ${{ matrix.os }} using ${{ matrix.mpi }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup MPI # https://github.com/mpi4py/setup-mpi
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -e .[ci]
      - name: Run tests with pytest (serial)
        run: |
          pytest -s tests/units
      - name: Run tests with pytest (parallel)
        run: |
          mpirun -n 2 pytest -s tests/units --with-mpi
